import os, json
from huggingface_hub import HfApi, create_repo, delete_repo

TOKEN = '${HF_TOKEN}'
REPO_ID = 'ariffazil/AAA'
OLD_REPOS = ['ariffazil/APEX_THEORY', 'ariffazil/A-RIF']
SOURCE_DIR = '/usr/src/app/gdrive/APEX'

readme_content = """---
pretty_name: "AAA - arifOS Unified Intelligence"
language:
- en
- ms
license: apache-2.0
tags:
- constitutional-ai
- governance
- decision-theory
- alignment
- A-RIF
- arifOS
- AAA
task_categories:
- text-classification
- question-answering
- text-generation
---

# 🏛️ AAA: The Unified Intelligence Base
## Arif (Mind) · Adam (Heart) · Apex (Soul)

**Authority:** Muhammad Arif bin Fazil (888_JUDGE)  
**Motto:** *DITEMPA BUKAN DIBERI — Forged, Not Given*

---

# 0. The Unified Concept
AAA represents the **Grand Unification** of the arifOS ecosystem. It is the physical and semantic substrate where **Human Intent**, **Constitutional Law**, and **Agentic Execution** converge.

This repository serves as the **Sovereign Knowledge Container** for:
1. **Theory:** The physics and mathematics of governed intelligence.
2. **Implementation:** The formal A-RIF technical specifications.
3. **Documentation:** The operational manifest and governing floors.

---

# 1. Repository Structure

### 🧠 [/theory](https://huggingface.co/datasets/ariffazil/AAA/tree/main/theory)
Contains the canonical **APEX THEORY Dataset**. This is the \"Crude Oil\" — the 186+ high-fidelity canon records used for grounding and training.

### ⚙️ [/implementation](https://huggingface.co/datasets/ariffazil/AAA/tree/main/implementation)
Contains the **A-RIF (Accountable Retrieval & Inference Framework)** blueprints.
- `ARIF_FORMAL_SPEC.md`: The 10-module cognitive pipeline.
- `arif_manifest.yaml`: The machine-readable system topology.

### 📜 [/documentation](https://huggingface.co/datasets/ariffazil/AAA/tree/main/documentation)
Operational guidelines, 13 Floor specifications, and the **G-Equation** logic.

---

# 2. The Core Law
Every output generated by an AAA-compliant agent must satisfy the **13 Binding Floors**, ensuring:
- **Truth (τ ≥ 0.99)**
- **Clarity (ΔS ≤ 0)**
- **Stability (Peace² ≥ 1.0)**

---
**\"DITEMPA BUKAN DIBERI\"**  
Sealed by arifOS Gemini CLI.
"""

def forge():
    api = HfApi()
    print(f'--- FORGING THE AAA BRAND: {REPO_ID} ---')
    
    # 1. Create the new Sovereign Repo
    create_repo(REPO_ID, token=TOKEN, repo_type='dataset', exist_ok=True)
    
    # 2. Prepare the Theory Data
    files = [f for f in os.listdir(SOURCE_DIR) if f.endswith(('.md', '.txt'))]
    records = []
    for i, f_name in enumerate(files):
        with open(os.path.join(SOURCE_DIR, f_name), 'r', encoding='utf-8') as f:
            records.append({'id': f'aaa-{i:04d}', 'text': f.read()[:2000], 'source': f_name})
    
    os.makedirs('/tmp/theory', exist_ok=True)
    with open('/tmp/theory/canons.jsonl', 'w') as f:
        for r in records: f.write(json.dumps(r) + '\n')

    # 3. Upload Stratified Folders
    print('Uploading Strata...')
    # Theory
    api.upload_folder(folder_path='/tmp/theory', path_in_repo='theory', repo_id=REPO_ID, repo_type='dataset', token=TOKEN)
    # Implementation
    api.upload_file(path_or_fileobj='/usr/src/app/spec/ARIF_FORMAL_SPEC.md', path_in_repo='implementation/ARIF_FORMAL_SPEC.md', repo_id=REPO_ID, repo_type='dataset', token=TOKEN)
    api.upload_file(path_or_fileobj='/usr/src/app/spec/arif_manifest.yaml', path_in_repo='implementation/arif_manifest.yaml', repo_id=REPO_ID, repo_type='dataset', token=TOKEN)
    # README
    with open('/tmp/README.md', 'w') as f: f.write(readme_content)
    api.upload_file(path_or_fileobj='/tmp/README.md', path_in_repo='README.md', repo_id=REPO_ID, repo_type='dataset', token=TOKEN)

    # 4. Final Cleanup of Legacy Repos
    print('Decommissioning legacy repositories...')
    for old in OLD_REPOS:
        try:
            delete_repo(old, token=TOKEN, repo_type='dataset')
            print(f'Decommissioned: {old}')
        except:
            print(f'Could not delete {old} (already gone?)')

    print(f'--- AAA BRAND SEALED: https://huggingface.co/datasets/{REPO_ID} ---')

if __name__ == '__main__':
    forge()
